[window]
opacity = 0.8
# padding = { y = 0 }

[scrolling]
history = 10000
multiplier = 3

[font]

# -- /home/antonioc/.local/share/fonts/

# normal = { family = "MesloLGS Nerd Font", style = "Regualar" }
# bold = { family = "MesloLGS Nerd Font", style = "Bold" }
# italic = { family = "MesloLGS Nerd Font", style = "Italic" }
# bold_italic = { family = "MesloLGS Nerd Font", style = "BoldItalic" }

normal = { family = "JetBrains Mono Nerd Font", style = "Regualar" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrains Mono Nerd Font", style = "BoldItalic" }

size = 11.2

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }
